port: 8080
files:
  cp-scheduling:
    label: "排课"
    path: "/apps/cp-scheduling/logs/cp-scheduling-test.log"
  wk-crm:
    label: "CRM"
    path: "/apps/wk-crm/logs/wk-crm.log"
  ca-studio:
    label: "花果"
    path: "/apps/ca-studio/logs/console.log"
  stu-center:
    label: "学员中心"
    path: "/apps/stu-center/logs/console.log"
  tch-studio:
    label: "老师工作室"
    path: "/apps/tch-studio/logs/console.log"
  cp-automation:
    label: "账务自动化"
    path: "/apps/cp-automation/logs/console.log"
  wk-talk-cloud:
    label: "拓课云"
    path: "/apps/wk-talk-cloud/logs/console.log"
  ms-e-commerce:
    label: "电商"
    path: "/apps/ms-e-commerce/logs/console.log"
  cp-gateway:
    label: "筋斗云"
    path: "/apps/cp-gateway/logs/console.log"
  cp-notification:
    label: "通知服务"
    path: "/apps/cp-notification/logs/console.log"
  ms-cms:
    label: "ms-cms"
    path: "/apps/ms-cms/logs/console.log"
  cp-public:
    label: "cp-public"
    path: "/apps/cp-public/logs/console.log"
  data-service:
    label: "data-service"
    path: "/apps/data-service/logs/console.log"
  ms-account:
    label: "账号C端"
    path: "/apps/ms-account/logs/console.log"
  ms-account-business:
    label: "账号B端"
    path: "/apps/ms-account-business/logs/console.log"
  ms-ai:
    label: "ms-ai"
    path: "/apps/ms-ai/logs/ms-ai-test.log"
  ms-course-resource:
    label: "ms-course-resource"
    path: "/apps/ms-course-resource/logs/console.log"
  ms-event-tracking:
    label: "埋点"
    path: "/apps/ms-event-tracking/logs/ms-event-tracking.log"
  ms-im:
    label: "ms-im"
    path: "/apps/ms-im/logs/console.log"
  ms-user:
    label: "ms-user"
    path: "/apps/ms-user/logs/ms-user.log"
  ms-wechat:
    label: "ms-wechat"
    path: "/apps/ms-wechat/logs/console.log"
  rs-gateway:
    label: "增长"
    path: "/apps/rs-gateway/logs/console.log"
  tch-learning-center:
    label: "tch-learning-center"
    path: "/apps/tch-learning-center/logs/tch-learning-center.log"
  tch-research:
    label: "教研"
    path: "/apps/tch-research/logs/console.log"
  teaching-admin:
    label: "teaching-admin"
    path: "/apps/teaching-admin/logs/console.log"
  wk-business-gateway:
    label: "网关B端"
    path: "/apps/wk-business-gateway/logs/wk-business-gateway.log"
  wk-classin:
    label: "wk-classin"
    path: "/apps/wk-classin/logs/console.log"
  wk-classroom-fail-safe:
    label: "应急服务"
    path: "/apps/wk-classroom-fail-safe/logs/console.log"
  wk-finance:
    label: "账务服务"
    path: "/apps/wk-finance/logs/wk-finance.log"
  wk-flowable:
    label: "工作流"
    path: "/apps/wk-flowable/logs/console.log"
  wk-gateway:
    label: "网关"
    path: "/apps/wk-gateway/logs/wk-gateway.log"
  wk-monitor-admin:
    label: "wk-monitor-admin"
    path: "/apps/wk-monitor-admin/logs/wk-admin-monitor.log"
  wk-reporting:
    label: "wk-reporting"
    path: "/apps/wk-reporting/logs/console.log"